# Generated by Django 5.2 on 2025-06-01 21:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('inn', models.CharField(max_length=100, unique=True, verbose_name='INN organizations')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Organization name')),
                ('address', models.CharField(blank=True, max_length=100, null=True, verbose_name='Organization address')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Balance')),
            ],
            options={
                'verbose_name': 'Organization',
                'verbose_name_plural': 'Organizations',
            },
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('operation_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Operation ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount')),
                ('document_number', models.CharField(max_length=64, verbose_name='Document number')),
                ('document_date', models.DateField(verbose_name='Document date')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Create date')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payments.organization', verbose_name='Organization')),
            ],
            options={
                'verbose_name': 'Operation',
                'verbose_name_plural': 'Operations',
            },
        ),
    ]
