repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.288
    hooks:
      - id: ruff
        args:
          - "--fix"
          - "--line-length=125"
        additional_dependencies: []

  - repo: https://github.com/psf/black
    rev: 24.1.0
    hooks:
      - id: black
        language_version: python3

  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: [ "--profile", "black" ]
